<?php $pageTitle='NotYVOS | Native x86-64 Operating System';$pageDescription='NotYVOS is a lightweight x86-64 operating system with a native desktop, persistent storage, hardware drivers and a PS3 runtime foundation.';$currentPage='home';require __DIR__.'/includes/header.php'; ?>
<main>
<section class="hero section-shell"><div class="hero-grid"><div class="hero-copy reveal"><span class="eyebrow">NOTYVOS PROJECT</span><h1>A native operating system built from the ground up.</h1><p class="hero-lead">NotYVOS is a lightweight x86-64 operating system with its own kernel, desktop environment, persistent storage, hardware support and an integrated PlayStation 3 runtime foundation.</p><div class="hero-actions"><a class="button primary" href="docs.php">Explore documentation</a><a class="button secondary" href="roadmap.php">View roadmap</a></div><div class="hero-meta"><span><b>C++20</b> kernel</span><span><b>x86-64</b> target</span><span><b>AGPL-3.0-or-later</b></span></div></div>
<div class="hero-visual reveal"><div class="orb orb-a"></div><div class="orb orb-b"></div><div class="logo-card"><img src="https://raw.githubusercontent.com/NotY215/NotYVOS/main/Assets/Neon%20Blue%20NotYVOS%20Tech%20Logo.png" alt="NotYVOS logo"><div class="scanline"></div><span>native / x86_64 / experimental</span></div></div></div></section>
<section class="section-shell section"><div class="section-heading reveal"><span class="eyebrow">WHAT IS INSIDE</span><h2>More than a kernel</h2><p>The project connects low-level platform code with a usable desktop and compatibility-oriented runtime components.</p></div><div class="card-grid three">
<article class="feature-card reveal"><span class="icon">01</span><h3>Kernel & memory</h3><p>x86-64 CPU setup, paging, heap, scheduler, user processes, syscalls and executable loading.</p><a href="architecture.php#kernel">Architecture →</a></article>
<article class="feature-card reveal"><span class="icon">02</span><h3>Desktop & graphics</h3><p>Compositor, windows, taskbar, Explorer, themes, TrueType rendering and a device-independent graphics path.</p><a href="architecture.php#graphics">Graphics stack →</a></article>
<article class="feature-card reveal"><span class="icon">03</span><h3>PS3 runtime</h3><p>PPU/SPU foundations, DMA, JIT, RSX software rendering, cellFs and GameRunner infrastructure.</p><a href="architecture.php#ps3">Runtime →</a></article>
</div></section>
<section class="section-shell section tinted"><div class="stats-grid"><div class="stat reveal"><strong>0–10F</strong><span>foundation frozen as delivered</span></div><div class="stat reveal"><strong>11</strong><span>TrueType subsystem delivered</span></div><div class="stat reveal"><strong>12</strong><span>Explorer and file operations delivered</span></div><div class="stat reveal"><strong>15A–15E</strong><span>USB and unified input delivered</span></div></div></section>
<section class="section-shell section"><div class="split"><div class="section-heading reveal"><span class="eyebrow">CURRENT MILESTONE</span><h2>Init program debugging</h2><p>The next active engineering target is the init program. The roadmap then continues into GameRunner, networking, Wi-Fi, Bluetooth, NYFS maturity, firewall work and NotYVFirm.</p><a class="text-link" href="roadmap.php">Read the full roadmap →</a></div><div class="terminal-card reveal"><div class="terminal-bar"><i></i><i></i><i></i><span>notyvos-status</span></div><pre><code>$ notyvos status
target: x86-64
kernel: delivered foundation
desktop: active
storage: NYFS + VFS
input: PS/2 + USB
next: init-program debugging
status: development</code></pre></div></div></section>
</main><?php require __DIR__.'/includes/footer.php'; ?>