<?php
$nav=['home'=>['Home','/'],'about'=>['About','/About/'],'architecture'=>['Architecture','/Architecture/'],'docs'=>['Documentation','/Documentation/'],'roadmap'=>['Roadmap','/Roadmap/'],'updates'=>['Updates','/Updates/'],'faq'=>['FAQ','/FAQ/'],'developer'=>['Developer','/Developer/']];
?>
<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#06101c"><meta name="description" content="<?= htmlspecialchars($pageDescription ?? 'NotYVOS operating system project website.') ?>"><meta name="robots" content="index,follow">
<title><?= htmlspecialchars($pageTitle ?? 'NotYVOS') ?></title>
<link rel="icon" type="image/png" href="https://raw.githubusercontent.com/NotY215/NotYVOS/main/Assets/Neon%20Blue%20NotYVOS%20Tech%20Logo.png"><link rel="apple-touch-icon" href="https://raw.githubusercontent.com/NotY215/NotYVOS/main/Assets/Neon%20Blue%20NotYVOS%20Tech%20Logo.png">
<link rel="canonical" href="<?= htmlspecialchars($canonicalUrl ?? "http://notyvos.gt.tc/") ?>"><link rel="stylesheet" href="/assets/css/style.css"><?php if (($currentPage ?? "") === "roadmap"): ?><link rel="stylesheet" href="/assets/css/roadmap.css?v=<?= rawurlencode(date("YmdHi")) ?>"><?php endif; ?><?php if (($currentPage ?? "") === "docs"): ?><?php $docsCssPath = __DIR__ . "/../assets/css/docs.css"; if (is_file($docsCssPath)) { echo "<style id="notyvos-docs-css">"; readfile($docsCssPath); echo "</style>"; } ?><?php endif; ?><script defer src="/assets/js/app.js"></script><script defer src="/assets/js/security.js"></script><meta property="og:title" content="<?= htmlspecialchars($pageTitle ?? "NotYVOS") ?>"><meta property="og:description" content="<?= htmlspecialchars($pageDescription ?? "NotYVOS operating system project website.") ?>"><meta property="og:url" content="<?= htmlspecialchars($canonicalUrl ?? "http://notyvos.gt.tc/") ?>"><meta property="og:type" content="website"></head>
<body><div class="site-bg" aria-hidden="true"><span></span><span></span><span></span></div>
<header class="site-header"><div class="nav-shell">
<a class="brand" href="/"><img src="https://raw.githubusercontent.com/NotY215/NotYVOS/main/Assets/Neon%20Blue%20NotYVOS%20Tech%20Logo.png" alt=""><span>NotYVOS</span></a>
<button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false"><span></span><span></span><span></span></button>
<nav class="main-nav" id="main-nav"><?php foreach($nav as $key=>$item): $label=$item[0]; $url=$item[1]; ?><a class="<?= $currentPage===$key?'active':'' ?>" href="<?= $url ?>"><?= htmlspecialchars($label) ?></a><?php endforeach; ?><a class="github-link" href="https://github.com/NotY215/NotYVOS" target="_blank" rel="noopener">GitHub ↗</a></nav>
</div></header>